### ISSUE TITLE
feature: doesNotInclude(word: array)

### ISSUE THREAD

**Issue by msimerson** [Heaty566/joi-password#9]
### Feature Request

I'd like an additional test lets me specify words to exclude. An example of usage:

```.js
  password: JoiPassword.string()
    .min(8)
    .max(30)
    .minOfSpecialCharacters(2)
    .minOfLowercase(2)
    .minOfUppercase(2)
    .minOfNumeric(2)
    .doesNotInclude(['password', 'qwerty', '123456', `abc123', `${u.username}`])
    .required(),

```

As you can see, I want to exclude the [most common passwords](https://en.wikipedia.org/wiki/List_of_the_most_common_passwords) as well as the user's username.

**Comment by Heaty566** [comment]
Thank you so much, I'm going to add this feature in the repo.

**Comment by Heaty566** [comment]
version 4.2.0 is ready, Thank you

**Comment by msimerson** [comment]
🙇🏼‍♂️ Thank you!
